accounts/urls.py
from django.urls import path
from . import views

urlpatterns=[path('login',views.login,name='login'),
             path('register',views.register,name='register')]

firstproject/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls')),
    path('client/',include('customers.urls')),
    path('',views.home,name='home')
]

customers/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Customers(models.Model):
	SELECT=''
	MALE='M'
	FEMALE='F'
	OTHERS='O'

	YES='Y'
	NO='N'

	gender_choices=[(SELECT,'Gender'),(MALE,'Male'),(FEMALE,'Female'),(OTHERS,'Others')]
	is_married_choices=[(SELECT,'Is Married'),(YES,'Yes'),(NO,'No')]

	name=models.CharField(max_length=50)
	father_name=models.CharField(max_length=50)
	mother_name=models.CharField(max_length=50)
	last_name=models.CharField(max_length=50)
	spouse_name=models.CharField(max_length=50,blank=True)
	gender=models.CharField(max_length=1,choices=gender_choices)
	is_married=models.CharField(max_length=1,choices=is_married_choices)
	dob=models.DateField()
	place_of_birth=models.CharField(max_length=25)
	correspondence_address=models.TextField(max_length=100)
	is_perm_same=models.BooleanField()
	permanent_address=models.TextField(max_length=100)	
	pan=models.CharField(max_length=10,unique=True,error_messages={'unique':'Customer with this pan already exists'})
	aadhar=models.CharField(max_length=12, unique=True,error_messages={'unique':'Customer with this aadhar already exists'})
	education=models.CharField(max_length=20)
	mobile=models.CharField(max_length=10)
	height=models.FloatField()
	weight=models.FloatField()
	username=models.CharField(max_length=150)

	def __str__(self):
		return str(self.id)


class Policies(models.Model):
	cid=models.ForeignKey('Customers',on_delete=models.CASCADE)
	policy_no=models.CharField(max_length=15,unique=True,null=False)
	term_plan=models.CharField(max_length=8)
	sum_assured=models.IntegerField()

templates/addClient.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <style>
        .bottomMargin{margin-bottom:12px}
        .errorlist{
        color:red;
        font-size:12px;
        }
    </style>
    <script>
    $(document).ready(function() {

    $('#id_is_perm_same').change(function() {
        if(this.checked) {
            $('#id_permanent_address').prop('readonly',true);
            $('#id_permanent_address').val($('#id_correspondence_address').val());
        }
        else{
            $('#id_permanent_address').prop('readonly',false);
            $('#id_permanent_address').val("");
        }
       
    });
    $('#id_correspondence_address').keyup(function() {
        
        if($('#id_is_perm_same').prop("checked")) {
            $('#id_permanent_address').val($('#id_correspondence_address').val());
        }
        
       
    });
    $('#id_is_married').change(function(){
        if($(this).val()=='Y'){
            $('#id_spouse_name').prop('required',true);
            $('#id_spouse_name').prop('readonly',false);
            } else {
                $('#id_spouse_name').prop('required',false);
                $('#id_spouse_name').val('');
                $('#id_spouse_name').prop('readonly',true);
            }
    
    });
});
    </script>
</head>
<body>
<div class="container-fluid">
    <div class="w3-container w3-right w3-xlarge"><a href="/client/dashboard">Dashboard</a> | <a href="/client/logout">Logout</a></div>
    <center style="margin:10px;font-size:20px;"><b>Customer Details</b></center>
    
    <div class="col-sm-offset-4  col-sm-4">
        
                {% if messages %}
                    {% for message in messages %}
                        <div class="{{message.tags}}">{{ message }}</div>
                    {% endfor %}
                {% endif %}
    </div>
    <form class="form-horizontal" action={% if is_modify %} "/client/modify/{{ cust_id }}" {% else %} "add" {% endif %} method="post">
        {% csrf_token %}
        <div class="form-group">
                {% for field in form %}
                <div class="col-sm-offset-4  col-sm-4">
                    {{ field.label_tag }}
                    {{  field }}
                    <span class="errorlist">{{ field.errors|striptags}}</span>
                </div>
                {% endfor %} 
            
        </div>
       
        <div class="form-group">
            <div class="col-sm-offset-4 col-sm-10">
                <input type="submit"  class="btn btn-primary"/>
            </div>
        </div>

    </form>
</div>

</body>
</html>

templates/dashboard.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <script>
        function searchCustomer() {

              var input, filter, table, tr, td, i, txtValue;
              input = document.getElementById("search");
              filter = input.value.toUpperCase();
              table = document.getElementById("customerTable");
              tr = table.getElementsByTagName("tr");

              // Loop through all table rows, and hide those who don't match the search query
              for (i = 0; i < tr.length; i++) {
                td = tr[i].getElementsByTagName("td")[1];
                if (td) {
                  txtValue = td.textContent || td.innerText;
                  if (txtValue.toUpperCase().indexOf(filter) > -1) {
                    tr[i].style.display = "";
                  } else {
                    tr[i].style.display = "none";
                  }
                }
              }
            }
    </script>
    <style>
        .bottomMargin{margin-bottom:12px}
    </style>
    
</head>
<body>
    <div class="container">
    <div class="row" style="margin-top:12px;margin-bottom:8px">
           <div class="col-xs-4"> <input type="text" onkeyup="searchCustomer()" id="search" class="form-control" placeholder="Search Customer by Name"></div>
            <div class="col text-right"><a href="/client/add" class="btn btn-default">New Customer</a> <a href="/client/logout" class="btn btn-default">Logout</a></div>
        </div>
        <div>
            <table id="customerTable" class="table table-bordered table-striped">
                <tr>
                    <th>Customer Id</th>
                    <th>Customer Name</th>
                    
                    <th>View/Edit Customer details</th>
                    <th>View/Add policies</th>
                    
                </tr>
                
               {% for cust in custs %}
                <tr>
                    <td>{{ cust.id }}</td>
                    <td>{{ cust.name  }} {{ cust.father_name }} {{ cust.last_name }}</td>
                   
                    <td><a href="/client/modify/{{ cust.id }}"><i class="glyphicon glyphicon-edit"></i></a></td>
                    <td><a href="/client/policy/show/{{ cust.id }}"><i class="glyphicon glyphicon-eye-open"></i></a>&nbsp&nbsp&nbsp&nbsp<a href="/client/policy/add/{{ cust.id }}"><i class="glyphicon glyphicon-plus"></i></a></td>
               </tr>
               {% endfor %}
               
            </div>
        </div>
    </div>
</body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <script>
         

    </script>
</head>
<body>
<div class="container-fluid">
    {% if not user.is_authenticated %}
        <center style="margin:10px;font-size:20px;"><a href="accounts/register" style="margin-right:50px">Register</a><a href="accounts/login">Login</a></center>
    
        
   {% endif %}
</div>

</body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <script>
      




    </script>
</head>
<body>

<div class="w3-card-4 w3-margin-top" style="margin:auto;width: 50%;height:300px">
    
    <center style="margin:10px;font-size:20px;padding-top:10px"><b>Login</b></center>
    <form class="form-horizontal" action="login" method="post">
     {% csrf_token %}
        <div class="form-group">
            <div class="col-sm-offset-4  col-sm-4">
                {{ form.username }}
            </div>
        </div>
        <strong id="uname_error" class="col-sm-offset-4 col-sm-4"
                style="display:block;color:red;margin-top:0px;margin-bottom:12px">{{ form.username.errors|striptags }}</strong>
        <div class="form-group">
            <div class="col-sm-offset-4 col-sm-4">
                {{ form.password }}
            </div>
        </div>
        <strong id="pwd_error" class="col-sm-offset-4 col-sm-4"
                style="display:block;color:red;margin-top:0px;margin-bottom:12px">{{ form.password.errors|striptags }}</strong>
        <div class="form-group">
            <div class="col-sm-offset-4 col-sm-10">
                <input type="submit" class="btn btn-primary"/>
            </div>
        </div>
         <div class="col-sm-offset-4 col-sm-10">
            {% if messages %}
                {% for message in messages %}
                    <h3 style="color:red">{{message}}</h3>
                {% endfor %}
            {% endif %}
        </div>
    </form>
    <div class="col-sm-offset-4 col-sm-10"><a  href="register">Not registered yet? Click to Register</a></div>

</div>


</body>
</html>

templates/policy.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <style>
        .bottomMargin{margin-bottom:12px}
        .errorlist{
        color:red;
        font-size:12px;
        }
    </style>
    <script>
    $(document).ready(function() {

    $('#id_is_perm_same').change(function() {
        if(this.checked) {
            $('#id_permanent_address').prop('readonly',true);
            $('#id_permanent_address').val($('#id_correspondence_address').val());
        }
        else{
            $('#id_permanent_address').prop('readonly',false);
            $('#id_permanent_address').val("");
        }
       
    });
    $('#id_correspondence_address').keyup(function() {
        
        if($('#id_is_perm_same').prop("checked")) {
            $('#id_permanent_address').val($('#id_correspondence_address').val());
        }
        
       
    });
    $('#id_is_married').change(function(){
        if($(this).val()=='Y'){
            $('#id_spouse_name').prop('required',true);
            $('#id_spouse_name').prop('readonly',false);
            } else {
                $('#id_spouse_name').prop('required',false);
                $('#id_spouse_name').val('');
                $('#id_spouse_name').prop('readonly',true);
            }
    
    });
});
    </script>
</head>
<body>
<div class="container-fluid">
    <div class="w3-container w3-right w3-xlarge"><a href="/client/dashboard">Dashboard</a> | <a href="/client/logout">Logout</a></div>
    <center style="margin:10px;font-size:20px;"><b>Policy Details</b></center>
    
    <div class="col-sm-offset-4  col-sm-4">
        
                {% if messages %}
                    {% for message in messages %}
                        <div class="{{message.tags}}">{{ message }}</div>
                    {% endfor %}
                {% endif %}
    </div>
    <form class="form-horizontal" action={% if is_modify %} "/client/policy/modify/{{ policy_id }}" {% else %} "/client/policy/add/{{ cust_id }}" {% endif %} method="post">
        {% csrf_token %}
        <div class="form-group">
                {% for field in form %}
                <div class="col-sm-offset-4  col-sm-4">
                    {{ field.label_tag }}<br>
                    {{  field }}<br>
                    <span class="errorlist">{{ field.errors|striptags}}</span>
                </div>
                {% endfor %} 
            
        </div>
       
        <div class="form-group">
            <div class="col-sm-offset-4 col-sm-10">
                <input type="submit"  class="btn btn-primary"/>
            </div>
        </div>

    </form>
</div>

</body>
</html>

templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
   
</head>
<body>
<div class="container-fluid">
    <center style="margin:10px;font-size:20px;"><b>Registration form</b></center>
    <form class="form-horizontal" action="register" method="post">
        {% csrf_token %}
        <div class="form-group">
            <div class="col-sm-offset-4 col-sm-4">
                {{ form.firstname }}
                <!--input type="text" class="form-control" id="fname" name="firstname" placeholder="First name"-->
            </div>
             <strong id="fname_error" class="col-sm-offset-4 col-sm-4"
                style="color:red;margin-top:0px">{{ form.firstname.errors|striptags }}</strong>
        </div>

        <div class="form-group">
            <div class="col-sm-offset-4 col-sm-4">
                {{ form.lastname }}
                <!--input type="text" class="form-control" id="lname" name="lastname" placeholder="Last name"-->
            </div>
            <strong id="lname_error" class="col-sm-offset-4 col-sm-4"
                style="color:red;margin-top:0px;">{{ form.lastname.errors|striptags }}</strong>
        
        </div>
        <div class="form-group">
            <div class="col-sm-offset-4  col-sm-4">
                {{ form.username }}
                <!--input type="text" class="form-control" id="uname" name="username" placeholder="Username"-->
            </div>
            <strong id="uname_error" class="col-sm-offset-4 col-sm-4"
                style="color:red;margin-top:0px;">{{ form.username.errors|striptags }}</strong>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-4 col-sm-4">
                {{ form.email }}
                <!--input type="email" class="form-control" id="email" name="email" placeholder="Email"-->
            </div>
            <strong id="email_error" class="col-sm-offset-4 col-sm-4"
                style="color:red;margin-top:0px;">{{ form.email.errors|striptags }}</strong>
        </div>

        <div class="form-group">
            <div class="col-sm-offset-4 col-sm-4">
                {{ form.password1 }}
                <!--input type="password" class="form-control" id="pwdd" name="password1" placeholder="Password"-->
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-4 col-sm-4">
                {{ form.password2 }}
                <!--input type="password" class="form-control" id="confpwd" name="password2" placeholder="Confirm password"-->
            </div>
            <strong id="pwd_error" class="col-sm-offset-4 col-sm-4"
                style="color:red;margin-top:0px;">{{ form.password2.errors|striptags }}</strong>
        </div>
     
        <div class="form-group">
            <div class="col-sm-offset-4 col-sm-10">
                <input type="submit" class="btn btn-primary"/>
            </div>
        </div>
        <div class="col-sm-offset-4 col-sm-10">
            {% if messages %}
                {% for message in messages %}
                    <h3 style="color:red">{{message}}</h3>
                {% endfor %}
            {% endif %}
        </div>
    </form>
    <div class="col-sm-offset-4 col-sm-10"><a  href="login">Already registered? Click to Login</a></div>
</div>

</body>
</html>

templates/show_policies.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <script>
        function searchPolicy() {

              var input, filter, table, tr, td, i, txtValue;
              input = document.getElementById("search");
              filter = input.value.toUpperCase();
              table = document.getElementById("policyTable");
              tr = table.getElementsByTagName("tr");

              // Loop through all table rows, and hide those who don't match the search query
              for (i = 0; i < tr.length; i++) {
                td = tr[i].getElementsByTagName("td")[1];
                if (td) {
                  txtValue = td.textContent || td.innerText;
                  if (txtValue.toUpperCase().indexOf(filter) > -1) {
                    tr[i].style.display = "";
                  } else {
                    tr[i].style.display = "none";
                  }
                }
              }
            }

            $(function () {
        $(".deleteButton").click(function () {
            var my_id_value = $(this).data('id');
            $(".modal-footer #btnConfDelete").attr("href",my_id_value);
        })
    });
    </script>
    
    <style>
        .bottomMargin{margin-bottom:12px}
    </style>
    
</head>
<body>
    <div class="container">
        
        <div class="row" style="margin-top:12px;margin-bottom:8px">
           <div class="col-xs-4">  <input type="text"onkeyup="searchPolicy()" id="search" class="form-control" placeholder="Search Policy"></div>
            <div class="col text-right"><a href="/client/dashboard" class="btn btn-default">Dashboard</a> <a href="/client/logout" class="btn btn-default">Logout</a></div>
        </div>
           
            
            <b>Customer Id: </b>{{ cust_id }}
        

        <div>
            <table class="table table-bordered table-striped" id="policyTable">
                <tr>
                    <th>Policy Id</th>
                    <th>Policy Number</th>
                    
                    <th>Term plan</th>
                    <th>Sum assured</th>
                    <th>Delete</th>
                   
                    
                </tr>
                
               {% for policy in policies %}
                <tr>
                    <td>{{ policy.id }}</td>
                    <td>{{ policy.policy_no }}</td>
                    <td>{{ policy.term_plan }}</td>
                    <td>{{ policy.sum_assured }}</td>
                    <td><a href="#" class="glyphicon glyphicon-trash deleteButton" data-id="/client/policy/delete/{{ policy.id }}" data-toggle="modal" data-target="#myModal"></a></td>
                    <!--td><a href="/client/policy/delete/{{ policy.id }}"><i class="glyphicon glyphicon-trash" data-toggle="modal" data-target="#myModal"></i></a></td-->

                    <!--td><a href="/client/modify/{{ cust.id }}"><i class="glyphicon glyphicon-edit"></i></a></td>
                    <td><a href="#"><i class="glyphicon glyphicon-eye-open"></i></a>&nbsp&nbsp&nbsp&nbsp<a href="/client/policy/add/{{ cust.id }}"><i class="glyphicon glyphicon-plus"></i></a></td-->
               </tr>
               {% endfor %}
               
            </div>
        </div>
    </div>

    <div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Delete policy</h4>
      </div>
      <div class="modal-body">
        <p>Do you want to delete the policy?</p>
      </div>
      <div class="modal-footer">
        <a id="btnConfDelete" class="btn btn-default">Yes</a>
        <button type="button" class="btn btn-default" data-dismiss="modal">No</button>
      </div>
    </div>

  </div>
</div>
</body>
</html>